feeds:
  - astro-ph
  - cond-mat
  - gr-qc
  - hep-ex
  - math-ph
  - nucl-ex
  - nucl-th
  - physics
  - quant-ph
  - math
  - cs        # CoRR
  - q-bio
  - stat
  - econ

max_items_per_feed: 50

threshold: 1.5

email_cap: 150
print_cap: 50